### ISSUE TITLE
Can't find winrar or 7z, despite the fact that i got both installed

### ISSUE THREAD

**Issue by Leha44581** [drobie22/RSS-Reborn-Installer#1]
It's all in the title
I will note, neither is located at the default filepaths
![image](https://github.com/user-attachments/assets/3ebb14b7-7b83-46d8-8f04-7a92666e2906)
![image](https://github.com/user-attachments/assets/660609ae-e63b-4613-9bd1-6528d0613b95)

**Comment by drobie22** [comment]
> I will note, neither is located at the default filepaths

Yeah that would be the issue. What location are they in, and if you don't mind me asking why not default?

Trying to see if it is worth adding a search in your directory if it is a common rationale.

Reason I only added a search in the default directory is because I not sure how necessary a computer wide search for 7 zip or WinRAR is.

**Comment by drobie22** [comment]
Version v1.0.2 is released, should fix issue!
